"""
topics_data.py — canonical data for all 36 debate topics.

Slugs match the actual folder names under docs/topics/.
Each entry:
  slug       — matches /topics/{slug}/ URL path exactly
  name       — display name
  category   — one of: "Core Theology", "Church Life", "Spiritual Formation", "Culture & Society"
  hook       — one punchy sentence capturing the central debate question
               (used on individual topic pages for SEO/AEO)
  summary    — short plain-language description of what the topic covers
               (used on homepage cards, digest cards, and emails — not tied to today's articles)
  keywords   — list of strings used by the topic classifier to match articles
"""

TOPICS = [
    # ── Core Theology ─────────────────────────────────────────────────────────
    {
        "slug": "atonement",
        "name": "The Atonement",
        "category": "Core Theology",
        "hook": "What exactly did Jesus' death accomplish — and how does it actually save us?",
        "summary": "Evangelical perspectives on the cross, penal substitution, and what Christ's death accomplished for sinners.",
        "keywords": [
            "atonement", "penal substitution", "substitutionary atonement", "cross of christ",
            "propitiation", "expiation", "reconciliation", "blood of christ",
            "christus victor", "moral influence", "ransom theory", "why jesus died",
        ],
    },
    {
        "slug": "justification-by-faith",
        "name": "Justification by Faith",
        "category": "Core Theology",
        "hook": "Is justification a declaration of righteousness, a process of becoming righteous, or something else?",
        "summary": "Evangelical debate over faith alone, imputed righteousness, and what Paul really meant by justification.",
        "keywords": [
            "justification", "sola fide", "faith alone", "imputed righteousness",
            "new perspective on paul", "wright", "forensic justification",
            "works of the law", "righteousness of god", "saved by faith",
        ],
    },
    {
        "slug": "biblical-inerrancy",
        "name": "Biblical Inerrancy",
        "category": "Core Theology",
        "hook": "Is the Bible without error in everything it affirms, or only in matters of faith and practice?",
        "summary": "How evangelicals understand Scripture's authority, reliability, and relationship to science, history, and theology.",
        "keywords": [
            "inerrancy", "infallibility", "biblical inerrancy", "scripture",
            "sola scriptura", "chicago statement", "biblical authority",
            "biblical inspiration", "word of god", "errancy",
            "hermeneutics", "biblical criticism", "canon",
        ],
    },
    {
        "slug": "baptism",
        "name": "Baptism",
        "category": "Core Theology",
        "hook": "Should we baptize infants or only those who profess faith — and does it matter?",
        "summary": "The evangelical debate over infant vs. believer's baptism, mode, and what Scripture teaches about the ordinance.",
        "keywords": [
            "baptism", "infant baptism", "paedobaptism", "credobaptism",
            "believer's baptism", "baptismal regeneration", "mode of baptism",
            "immersion", "sprinkling", "baptize", "christening",
        ],
    },
    {
        "slug": "lords-supper",
        "name": "The Lord's Supper",
        "category": "Core Theology",
        "hook": "Is Christ truly present in the bread and cup, and if so, how?",
        "summary": "Evangelical perspectives on what happens at communion — Christ's presence, meaning, and how churches practice it.",
        "keywords": [
            "lord's supper", "communion", "eucharist", "real presence",
            "transubstantiation", "consubstantiation", "memorial",
            "breaking bread", "table of the lord", "sacrament", "ordinance",
        ],
    },
    {
        "slug": "heaven-hell-eternity",
        "name": "Heaven, Hell & Eternity",
        "category": "Core Theology",
        "hook": "Is hell a place of eternal conscious torment, or does God eventually destroy the lost?",
        "summary": "Evangelical views on the afterlife, eternal punishment, annihilationism, and the hope of new creation.",
        "keywords": [
            "hell", "heaven", "eternal punishment", "annihilationism",
            "conditional immortality", "universalism", "purgatory",
            "gehenna", "lake of fire", "eternal life", "new creation",
            "resurrection", "final judgment", "eternity",
        ],
    },
    {
        "slug": "creation-evolution",
        "name": "Creation & Evolution",
        "category": "Core Theology",
        "hook": "Did God create the universe in six literal days, or is Genesis compatible with modern science?",
        "summary": "How evangelicals navigate Genesis, the origins debate, and young-earth vs. old-earth creationism.",
        "keywords": [
            "creation", "evolution", "creationism", "intelligent design", "genesis",
            "young earth", "old earth", "day-age", "theistic evolution",
            "origins", "darwinism", "adam and eve", "historical adam",
            "biologos", "framework hypothesis",
        ],
    },
    {
        "slug": "suffering-and-providence",
        "name": "Suffering & Providence",
        "category": "Core Theology",
        "hook": "Does God ordain suffering for our good, or does he merely permit it?",
        "summary": "How Christians understand God's sovereignty in the face of pain, grief, and seemingly unanswered prayer.",
        "keywords": [
            "suffering", "providence", "theodicy", "problem of evil",
            "why does god allow", "grief", "lament",
            "god's plan", "ordained suffering", "open theism",
            "meticulous providence", "sovereignty of god",
        ],
    },
    {
        "slug": "gender-and-biblical-anthropology",
        "name": "Gender & Biblical Anthropology",
        "category": "Core Theology",
        "hook": "What does Scripture teach about what it means to be male and female?",
        "summary": "Evangelical perspectives on male and female identity, embodiment, transgender questions, and the image of God.",
        "keywords": [
            "gender", "male and female", "biblical anthropology", "human sexuality",
            "transgender", "gender identity", "sex and gender", "image of god",
            "embodiment", "what is a woman", "biological sex", "imago dei",
        ],
    },
    {
        "slug": "apologetics",
        "name": "Apologetics",
        "category": "Core Theology",
        "hook": "Should Christians defend the faith through reason and evidence, or simply proclaim the gospel?",
        "summary": "How Christians make the case for the faith — through reason, evidence, presupposition, and engagement with doubt.",
        "keywords": [
            "apologetics", "defense of the faith", "presuppositional",
            "classical apologetics", "evidentialism", "natural theology",
            "reason and faith", "evidence for christianity", "atheism",
            "skepticism", "doubt", "intellectual defense",
        ],
    },

    # ── Church Life ────────────────────────────────────────────────────────────
    {
        "slug": "complementarianism-egalitarianism",
        "name": "Complementarianism & Egalitarianism",
        "category": "Church Life",
        "hook": "Should women serve as pastors and elders, or are those roles reserved for men?",
        "summary": "The ongoing evangelical debate over women in ministry, male headship, and what Scripture teaches about church leadership.",
        "keywords": [
            "complementarian", "egalitarian", "women in ministry", "women pastor",
            "female pastor", "ordination of women", "women preaching",
            "women elders", "male headship", "1 timothy 2",
            "women in church", "biblical womanhood", "biblical manhood",
        ],
    },
    {
        "slug": "church-discipline",
        "name": "Church Discipline",
        "category": "Church Life",
        "hook": "When and how should a church remove a member — and what does restoration look like?",
        "summary": "How churches handle member sin, accountability, corrective removal, and the path to restoration.",
        "keywords": [
            "church discipline", "excommunication", "disfellowship", "Matthew 18",
            "church membership", "accountability", "rebuke", "restore",
            "wayward member", "sin in the church", "corrective discipline",
        ],
    },
    {
        "slug": "worship-and-liturgy",
        "name": "Worship & Liturgy",
        "category": "Church Life",
        "hook": "Should evangelical worship be free-form and contemporary, or anchored in historic liturgical forms?",
        "summary": "Evangelical conversation about how churches should gather, sing, and meet with God — contemporary or liturgical.",
        "keywords": [
            "worship", "liturgy", "liturgical", "contemporary worship", "hymns",
            "regulative principle", "normative principle", "corporate worship",
            "worship music", "church music", "worship wars",
            "contemporary christian music", "CCM",
        ],
    },
    {
        "slug": "local-church",
        "name": "The Local Church",
        "category": "Church Life",
        "hook": "Is belonging to a local church optional for Christians, or essential to spiritual health?",
        "summary": "Why the local church matters — and evangelical conversations about attendance, belonging, and dechurching.",
        "keywords": [
            "local church", "church attendance", "ecclesiology",
            "church planting", "multisite", "megachurch", "dechurching",
            "leaving church", "church body", "fellowship", "gathered church",
            "unchurched", "why church matters",
        ],
    },
    {
        "slug": "missions-and-evangelism",
        "name": "Missions & Evangelism",
        "category": "Church Life",
        "hook": "What is the church's primary mission — gospel proclamation, or social transformation?",
        "summary": "How evangelicals understand the Great Commission, gospel proclamation, and the church's mission in the world.",
        "keywords": [
            "missions", "evangelism", "missionaries", "great commission",
            "gospel proclamation", "social gospel", "holistic mission",
            "unreached peoples", "cross-cultural", "missiology",
            "contextualization", "evangelism method",
        ],
    },
    {
        "slug": "church-history",
        "name": "Church History",
        "category": "Church Life",
        "hook": "How should evangelical churches relate to the wisdom — and failures — of their historical ancestors?",
        "summary": "What the church's past — its reformers, councils, creeds, and failures — means for Christians today.",
        "keywords": [
            "church history", "reformation", "reformers", "puritans",
            "luther", "calvin", "augustine", "early church", "church fathers",
            "protestant", "medieval church", "historical theology",
            "councils", "creeds", "confessions",
        ],
    },
    {
        "slug": "membership",
        "name": "Church Membership",
        "category": "Church Life",
        "hook": "Is formal church membership a biblical requirement or an optional formality?",
        "summary": "Evangelical perspectives on formal church membership and what covenant commitment to a local body requires.",
        "keywords": [
            "church membership", "formal membership", "covenant membership",
            "joining a church", "membership class", "church commitment",
            "membership vows", "member covenant",
        ],
    },
    {
        "slug": "church-planting",
        "name": "Church Planting",
        "category": "Church Life",
        "hook": "Is planting new churches the best strategy for reaching new communities?",
        "summary": "The theology and practice of starting new churches as a strategy for reaching unchurched communities.",
        "keywords": [
            "church planting", "church plant", "church planter",
            "new church", "starting a church", "Acts 29",
            "church multiplication", "replanting", "revitalization",
        ],
    },
    {
        "slug": "preaching",
        "name": "Preaching",
        "category": "Church Life",
        "hook": "What makes preaching faithful — and is expository preaching the only legitimate approach?",
        "summary": "What makes a sermon faithful — evangelical debate over expository preaching, topical approaches, and pulpit method.",
        "keywords": [
            "preaching", "expository preaching", "sermon", "homiletics",
            "topical preaching", "expository", "preach", "pulpit",
            "faithful preaching", "biblical preaching", "narrative preaching",
        ],
    },

    # ── Spiritual Formation ────────────────────────────────────────────────────
    {
        "slug": "prayer",
        "name": "Prayer",
        "category": "Spiritual Formation",
        "hook": "Does prayer change what God does, or does it primarily change us?",
        "summary": "Evangelical perspectives on how Christians pray, whether prayer changes things, and building a consistent prayer life.",
        "keywords": [
            "prayer", "intercession", "pray", "petition", "contemplative prayer",
            "prayer life", "praying", "unanswered prayer",
            "persistence in prayer", "prayer and sovereignty",
        ],
    },
    {
        "slug": "discipleship",
        "name": "Discipleship",
        "category": "Spiritual Formation",
        "hook": "What does it actually mean to make disciples — and are most churches doing it?",
        "summary": "How Christians grow in maturity — one-on-one mentoring, church programs, and the meaning of making disciples.",
        "keywords": [
            "discipleship", "disciple-making", "spiritual growth",
            "Christian formation", "mentoring", "one-on-one discipleship",
            "discipleship program", "making disciples",
        ],
    },
    {
        "slug": "sanctification",
        "name": "Sanctification",
        "category": "Spiritual Formation",
        "hook": "Is growing in holiness primarily God's work in us, or does it require rigorous human effort?",
        "summary": "The evangelical debate over how Christians grow in holiness — God's work, human effort, and means of grace.",
        "keywords": [
            "sanctification", "holiness", "mortification", "means of grace",
            "growing in holiness", "put to death", "spiritual maturity",
            "transformation", "progressive sanctification", "definitive sanctification",
        ],
    },
    {
        "slug": "spiritual-disciplines",
        "name": "Spiritual Disciplines",
        "category": "Spiritual Formation",
        "hook": "Are the spiritual disciplines a path to growth — or a path to legalism?",
        "summary": "How practices like solitude, silence, Scripture reading, and fasting shape the Christian life.",
        "keywords": [
            "spiritual disciplines", "disciplines", "solitude",
            "scripture memorization", "journaling", "sabbath keeping",
            "richard foster", "dallas willard", "means of grace",
        ],
    },
    {
        "slug": "spiritual-warfare",
        "name": "Spiritual Warfare",
        "category": "Spiritual Formation",
        "hook": "How active is demonic activity in the everyday lives of Christians?",
        "summary": "Evangelical perspectives on demonic activity, the armor of God, deliverance, and living in spiritual conflict.",
        "keywords": [
            "spiritual warfare", "spiritual battle", "satan", "demonic", "demons",
            "devil", "spiritual forces", "armor of god", "deliverance",
            "principalities", "powers", "evil one", "spiritual attack",
        ],
    },
    {
        "slug": "fasting",
        "name": "Fasting",
        "category": "Spiritual Formation",
        "hook": "Is fasting a neglected discipline the church must recover, or a practice easily misunderstood?",
        "summary": "What the Bible teaches about fasting — and why many evangelicals consider it a neglected spiritual discipline.",
        "keywords": [
            "fasting", "fast", "biblical fasting", "spiritual fast",
            "abstinence", "lent", "abstain from food",
        ],
    },
    {
        "slug": "anxiety-and-fear",
        "name": "Anxiety & Fear",
        "category": "Spiritual Formation",
        "hook": "Is anxiety primarily a spiritual failure, a medical condition, or both?",
        "summary": "How Christians understand worry, fear, and anxiety — spiritually, psychologically, and practically.",
        "keywords": [
            "anxiety", "worry", "anxious", "panic",
            "cast your anxiety", "do not be afraid", "mental health",
            "christian counseling", "psychology", "therapy",
        ],
    },
    {
        "slug": "mental-health",
        "name": "Mental Health & Faith",
        "category": "Spiritual Formation",
        "hook": "How should Christians think about depression and mental illness — as primarily spiritual, medical, or both?",
        "summary": "Evangelical perspectives on depression, mental illness, counseling, and integrating faith with psychological care.",
        "keywords": [
            "mental health", "depression", "mental illness", "christian mental health",
            "psychiatry", "antidepressants", "counseling", "suicide",
            "bipolar", "trauma", "emotional health", "psychology and faith",
        ],
    },

    # ── Culture & Society ──────────────────────────────────────────────────────
    {
        "slug": "politics-and-the-church",
        "name": "Politics & the Church",
        "category": "Culture & Society",
        "hook": "Should evangelical Christians seek political power, or hold it at arm's length?",
        "summary": "How evangelical Christians engage with politics, government, civic life, and the public square.",
        "keywords": [
            "christian nationalism", "politics", "political", "government",
            "election", "voting", "church and state", "two kingdoms",
            "common good", "public square", "political theology",
            "civic engagement", "democracy",
        ],
    },
    {
        "slug": "racial-reconciliation",
        "name": "Racial Reconciliation",
        "category": "Culture & Society",
        "hook": "Is racial reconciliation best pursued through structural change, individual repentance, or gospel proclamation?",
        "summary": "Evangelical conversation around race, repentance, diversity, and what the church owes to justice.",
        "keywords": [
            "racial reconciliation", "racism", "diversity",
            "social justice", "critical race theory", "CRT",
            "reparations", "racial justice", "multiethnic church",
            "ethnic diversity", "systemic racism",
        ],
    },
    {
        "slug": "technology",
        "name": "Technology & the Christian Life",
        "category": "Culture & Society",
        "hook": "How should Christians navigate a world increasingly shaped by technology and social media?",
        "summary": "How Christians think about social media, smartphones, digital life, and the spiritual formation impact of technology.",
        "keywords": [
            "technology", "social media", "smartphone", "digital",
            "internet", "algorithm", "screen time",
            "digital age", "online life", "phone",
        ],
    },
    {
        "slug": "technology-and-discipleship",
        "name": "Technology & Discipleship",
        "category": "Culture & Society",
        "hook": "How do smartphones and social media form us spiritually — and what should Christians do about it?",
        "summary": "How AI and digital tools are reshaping discipleship, ministry, and evangelical thinking about what it means to be human.",
        "keywords": [
            "artificial intelligence", "AI", "machine learning", "chatbot",
            "ChatGPT", "automation", "digital discipleship",
            "technology and discipleship", "tech and faith",
        ],
    },
    {
        "slug": "marriage-and-family",
        "name": "Marriage & Family",
        "category": "Culture & Society",
        "hook": "What does a distinctively Christian vision of marriage and family look like in a post-Christian culture?",
        "summary": "A Christian vision of marriage, family, divorce, singleness, and family formation in a post-Christian culture.",
        "keywords": [
            "marriage", "family", "husband", "wife",
            "divorce", "remarriage", "singleness", "celibacy",
            "same-sex marriage", "cohabitation", "family formation",
            "definition of marriage",
        ],
    },
    {
        "slug": "christian-parenting",
        "name": "Christian Parenting",
        "category": "Culture & Society",
        "hook": "How do Christian parents faithfully pass on faith to the next generation?",
        "summary": "How Christian parents pass faith to the next generation — from family worship and catechism to raising teenagers.",
        "keywords": [
            "parenting", "christian parenting", "raising children",
            "children and faith", "family worship", "catechism",
            "passing on faith", "prodigal children", "parenting teenagers",
        ],
    },
    {
        "slug": "christian-ethics",
        "name": "Christian Ethics",
        "category": "Culture & Society",
        "hook": "How do Christians navigate complex moral questions the Bible does not directly address?",
        "summary": "How Christians navigate bioethics, sexuality, LGBTQ+ questions, and moral issues with Biblical discernment.",
        "keywords": [
            "ethics", "bioethics", "moral", "abortion", "euthanasia",
            "end of life", "IVF", "surrogacy", "sexuality",
            "LGBTQ", "natural law", "moral theology", "christian ethics",
        ],
    },
    {
        "slug": "vocation-and-work",
        "name": "Vocation & Work",
        "category": "Culture & Society",
        "hook": "Is all honest work sacred, or does ministry hold a higher calling?",
        "summary": "Evangelical perspectives on calling, vocation, and how faith shapes ordinary work and the marketplace.",
        "keywords": [
            "vocation", "calling", "career", "workplace",
            "ordinary work", "sacred and secular",
            "faith and work", "monday morning", "marketplace", "profession",
        ],
    },
    {
        "slug": "evangelicalism",
        "name": "The Future of Evangelicalism",
        "category": "Culture & Society",
        "hook": "Is the evangelical movement fracturing — and if so, what should come next?",
        "summary": "The state of the evangelical movement — its divisions, decline, identity, and what comes next.",
        "keywords": [
            "evangelicalism", "evangelical", "post-evangelical",
            "evangelical identity", "evangelical decline", "evangelical movement",
            "SBC", "southern baptist", "NAE", "evangelical crisis",
        ],
    },
    {
        "slug": "predestination-free-will",
        "name": "Predestination & Free Will",
        "category": "Core Theology",
        "hook": "Is salvation ultimately determined by God's sovereign choice or the human will's free response — and what are the stakes of getting this question right?",
        "summary": "The Calvinist-Arminian debate over divine election, human freedom, and the nature of saving grace.",
        "keywords": [
            "predestination", "election", "calvinism", "arminianism", "free will",
            "sovereignty of god", "TULIP", "Reformed", "Molinism", "unconditional election",
            "middle knowledge", "libertarian freedom", "divine foreknowledge",
        ],
    },
    {
        "slug": "holy-spirit-spiritual-gifts",
        "name": "The Holy Spirit & Spiritual Gifts",
        "category": "Core Theology",
        "hook": "Do miraculous spiritual gifts like tongues and prophecy continue today, or did they cease with the apostolic age — and how does the answer shape Christian life and worship?",
        "summary": "The debate between cessationists and continuationists over spiritual gifts, tongues, and the Spirit's work today.",
        "keywords": [
            "holy spirit", "spiritual gifts", "tongues", "prophecy", "gifts of the spirit",
            "cessationism", "continuationism", "baptism in the holy spirit",
            "charismatic", "pentecostal", "apostolic gifts", "healing",
        ],
    },
    {
        "slug": "the-trinity",
        "name": "The Trinity",
        "category": "Core Theology",
        "hook": "What does it mean that God is one being in three persons — and why does Trinitarian theology matter for prayer, salvation, and everyday Christian life?",
        "summary": "Evangelical theology of the triune God — Father, Son, and Spirit — and why Trinitarian doctrine matters in practice.",
        "keywords": [
            "trinity", "trinitarian", "three in one", "father son holy spirit",
            "subordinationism", "social trinitarianism", "substance", "persons",
            "perichoresis", "divine nature", "godhead", "triune god",
        ],
    },
    {
        "slug": "christian-nationalism",
        "name": "Christian Nationalism",
        "category": "Culture & Society",
        "hook": "What is Christian nationalism, why is it attracting evangelical support, and how does it differ from faithful Christian political engagement?",
        "summary": "Evangelical debate over Christian nationalism — its appeal, its dangers, and what faithful political engagement looks like.",
        "keywords": [
            "christian nationalism", "nationalism", "christendom", "christian civilization",
            "christian right", "political power", "kingdom of god", "two kingdoms",
            "cultural christianity", "post-christian", "religious liberty",
        ],
    },
    {
        "slug": "faith-deconstruction",
        "name": "Deconstruction & Faith",
        "category": "Spiritual Formation",
        "hook": "When Christians begin questioning their beliefs, what does faithful deconstruction look like — and how should churches and pastors respond?",
        "summary": "Why Christians are deconstructing, what churches can do, and what healthy faith rebuilding looks like.",
        "keywords": [
            "deconstruction", "deconversion", "faith crisis", "questioning faith",
            "leaving evangelicalism", "religious trauma", "faith doubt", "apostasy",
            "doubting believer", "evangelical trauma", "reconstructing faith",
        ],
    },
    {
        "slug": "biblical-sexuality",
        "name": "Biblical Sexuality",
        "category": "Culture & Society",
        "hook": "What does Scripture teach about same-sex attraction, marriage, and sexual identity — and how should evangelical churches care for LGBTQ+ neighbors and members?",
        "summary": "Evangelical perspectives on same-sex attraction, LGBTQ+ identity, sexual ethics, and what Scripture teaches about sexuality.",
        "keywords": [
            "sexuality", "same-sex", "LGBTQ", "homosexuality", "gender identity",
            "sexual ethics", "traditional marriage", "sexual orientation",
            "conversion therapy", "celibacy", "affirming churches",
        ],
    },
    {
        "slug": "church-accountability",
        "name": "Pastoral Accountability",
        "category": "Church Life",
        "hook": "How should evangelical churches build structures that protect the vulnerable, hold leaders accountable, and prevent the abuse of power?",
        "summary": "How churches build structures to prevent pastoral abuse, protect victims, and hold leaders accountable.",
        "keywords": [
            "pastoral abuse", "accountability", "church discipline", "abuse prevention",
            "leadership structure", "elder boards", "abuse", "misconduct",
            "victim protection", "clergy abuse", "spiritual abuse",
        ],
    },
    {
        "slug": "contemplative-prayer",
        "name": "Contemplative Prayer",
        "category": "Spiritual Formation",
        "hook": "Are contemplative practices like centering prayer and lectio divina a rich retrieval of Christian tradition — or a dangerous import of mystical techniques incompatible with evangelical theology?",
        "summary": "Evangelical debate over centering prayer, lectio divina, and the place of contemplative practices in Christian spirituality.",
        "keywords": [
            "contemplative prayer", "centering prayer", "lectio divina", "mysticism",
            "contemplation", "meditation", "listening to god",
            "prayer of examen", "contemplative spirituality", "mystical theology",
        ],
    },
    {
        "slug": "ai-and-the-church",
        "name": "Artificial Intelligence & the Church",
        "category": "Culture & Society",
        "hook": "How should Christians think about AI's impact on ministry, human dignity, creative work, and what it means to be made in the image of God?",
        "summary": "How AI is reshaping ministry, creative work, and evangelical thinking about human dignity and the image of God.",
        "keywords": [
            "artificial intelligence", "AI", "chatGPT", "machine learning",
            "technology", "automation", "human dignity", "image of god",
            "algorithmic", "digital ministry", "technology and faith",
        ],
    },
    {
        "slug": "biblical-justice",
        "name": "Biblical Justice & the Social Gospel",
        "category": "Culture & Society",
        "hook": "What is the evangelical responsibility toward the poor and oppressed — and how do we distinguish biblical justice from a social gospel that eclipses the gospel itself?",
        "summary": "Evangelical debate over poverty, oppression, and the distinction between biblical justice and the social gospel.",
        "keywords": [
            "social justice", "poverty", "poor", "oppressed",
            "social gospel", "systemic injustice", "prophetic", "inequality",
            "racial justice", "economic justice", "biblical justice",
        ],
    },

    # ── New Topics (April 2026) ────────────────────────────────────────────────
    {
        "slug": "eschatology",
        "name": "Eschatology & End Times",
        "category": "Core Theology",
        "hook": "Will Christ return before, during, or after a thousand-year reign — and does your eschatology change how you live now?",
        "summary": "Evangelical debate over premillennialism, amillennialism, the rapture, and what Scripture teaches about Christ's return and the end of history.",
        "keywords": [
            "eschatology", "end times", "second coming", "rapture",
            "premillennialism", "amillennialism", "postmillennialism",
            "dispensationalism", "millennium", "tribulation",
            "revelation 20", "last days", "christ's return", "prophecy",
        ],
    },
    {
        "slug": "prosperity-gospel",
        "name": "The Prosperity Gospel",
        "category": "Culture & Society",
        "hook": "Does God promise health and wealth to the faithful — or is the prosperity gospel a dangerous distortion of Christ?",
        "summary": "Why evangelical Christians oppose the Word of Faith movement, and what a biblically faithful theology of blessing, suffering, and money looks like.",
        "keywords": [
            "prosperity gospel", "word of faith", "health and wealth gospel",
            "joel osteen", "kenneth copeland", "name it claim it",
            "positive confession", "false teaching", "american gospel",
            "prosperity theology", "seed offering", "word faith movement",
        ],
    },
    {
        "slug": "spiritual-abuse",
        "name": "Spiritual Abuse & Toxic Churches",
        "category": "Church Life",
        "hook": "How do churches recognize and respond to spiritual abuse — and why does it so often go unaddressed?",
        "summary": "What spiritual abuse looks like in evangelical churches, how abusive leaders operate, and what faithful churches owe to survivors.",
        "keywords": [
            "spiritual abuse", "toxic church", "abusive pastor", "spiritual manipulation",
            "religious trauma", "church trauma", "narcissism church",
            "controlling church", "chuck degroat", "wade mullen",
            "diane langberg", "pastoral abuse", "spiritual coercion", "toxic leadership",
        ],
    },
    {
        "slug": "religious-liberty",
        "name": "Religious Liberty",
        "category": "Culture & Society",
        "hook": "Is religious liberty under genuine threat — and how should Christians respond when conscience conflicts with the law?",
        "summary": "Evangelical debate over conscience rights, religious exemptions, government overreach, and how Christians engage a pluralistic legal culture.",
        "keywords": [
            "religious liberty", "religious freedom", "conscience rights",
            "religious exemption", "church and state", "first amendment",
            "pluralism and faith", "lgbtq religious exemptions",
            "faith and law", "ERLC", "andrew walker",
            "government and church", "christian civil engagement",
        ],
    },
    {
        "slug": "israel-and-prophecy",
        "name": "Israel & Prophecy",
        "category": "Core Theology",
        "hook": "Does the modern state of Israel fulfill biblical prophecy — and what do the Old Testament land promises mean for Christians today?",
        "summary": "Evangelical debate between dispensationalism and covenant theology over Israel's role in prophecy, the land promises, and Christian Zionism.",
        "keywords": [
            "israel prophecy", "dispensationalism", "covenant theology",
            "christian zionism", "land promises", "replacement theology",
            "supersessionism", "ezekiel 38", "israel bible prophecy",
            "israel church relationship", "middle east prophecy",
            "michael vlach", "joel rosenberg", "gog and magog",
        ],
    },
    {
        "slug": "grief-and-lament",
        "name": "Grief & Lament",
        "category": "Spiritual Formation",
        "hook": "Is lament a failure of faith — or does Scripture call suffering Christians to honest, anguished prayer?",
        "summary": "What the Bible teaches about grief, lament, and honest prayer in suffering — and why so many evangelical churches struggle to make space for it.",
        "keywords": [
            "lament", "grief", "psalms of lament", "theology of lament",
            "biblical grief", "mark vroegop", "dark clouds deep mercy",
            "jerry sittser", "psalm 42", "psalm 88",
            "job suffering", "lamentations", "honest prayer", "christian grief",
        ],
    },
    {
        "slug": "forgiveness",
        "name": "Forgiveness",
        "category": "Spiritual Formation",
        "hook": "Is Christian forgiveness unconditional — or must it require repentance from the offender?",
        "summary": "Evangelical debate over whether forgiveness is unconditional, what reconciliation requires, and how churches handle forgiveness in the context of abuse and justice.",
        "keywords": [
            "forgiveness", "christian forgiveness", "unconditional forgiveness",
            "forgiveness and repentance", "reconciliation", "chris brauns",
            "unpacking forgiveness", "matthew 18", "forgiveness and justice",
            "self-forgiveness", "forgiveness abuse", "bitterness",
            "forgive as god forgives",
        ],
    },
    {
        "slug": "progressive-christianity",
        "name": "Progressive Christianity",
        "category": "Culture & Society",
        "hook": "Is progressive Christianity a reform of the faith — or has it progressed so far it has become a different religion altogether?",
        "summary": "Evangelical responses to progressive Christianity — its departure from biblical authority, sexual ethics, and exclusivity — and what distinguishes it from historic orthodoxy.",
        "keywords": [
            "progressive Christianity", "progressive christian",
            "alisa childers", "another gospel", "rachel held evans",
            "rob bell", "brian mclaren", "emerging church",
            "deconstruction", "biblical authority", "affirming churches",
            "evangelical critique", "post-evangelical", "theological liberalism",
        ],
    },
    {
        "slug": "christian-friendship",
        "name": "Christian Friendship & Community",
        "category": "Spiritual Formation",
        "hook": "Why are deep friendships so rare in evangelical churches — and what does Scripture teach about the community we were made for?",
        "summary": "Evangelical perspectives on biblical friendship, loneliness, and why the church must become a place of genuine, deep relational belonging.",
        "keywords": [
            "christian friendship", "biblical friendship", "loneliness church",
            "christian community", "wesley hill", "spiritual friendship",
            "jonathan holmes", "church belonging", "gospel community",
            "christian loneliness", "single christian community",
            "isolation church", "community discipleship",
        ],
    },
    # ── Topics added to reach 70 ──────────────────────────────────────────────

    # Core Theology
    {
        "slug": "christology",
        "name": "Christology",
        "category": "Core Theology",
        "hook": "Is Jesus fully God and fully human at the same time — and why does the answer matter for salvation, prayer, and everything else?",
        "summary": "Evangelical theology of Jesus Christ — his divine and human natures, the hypostatic union, and what faithful Christology means for worship and salvation.",
        "keywords": [
            "christology", "jesus christ", "hypostatic union", "two natures",
            "fully god fully human", "incarnation", "divine nature", "human nature",
            "kenosis", "eternal son", "person of christ", "high christology",
            "deity of christ", "humanity of christ",
        ],
    },
    {
        "slug": "covenant-theology",
        "name": "Covenant Theology",
        "category": "Core Theology",
        "hook": "Is the Bible best read as one unified covenant story, or as a sequence of distinct dispensations — and what's at stake in getting this right?",
        "summary": "Evangelical debate between covenant theology and dispensationalism over how the Old and New Testaments relate, and what the biblical covenants mean for the church today.",
        "keywords": [
            "covenant theology", "dispensationalism", "new covenant", "old covenant",
            "covenant of grace", "covenant of works", "biblical theology",
            "law and gospel", "continuity discontinuity", "kingdom of god",
            "progressive covenantalism", "covenant", "testament",
        ],
    },

    # Church Life
    {
        "slug": "small-groups",
        "name": "Small Groups",
        "category": "Church Life",
        "hook": "Are small groups the engine of discipleship in the local church — or a poor substitute for the deep community Christians actually need?",
        "summary": "How evangelical churches use small groups, life groups, and home groups for discipleship, community, and pastoral care — and whether they actually work.",
        "keywords": [
            "small groups", "life groups", "home groups", "community groups",
            "cell groups", "small group ministry", "house church",
            "missional community", "discipleship groups", "bible study group",
            "small group leader", "small group curriculum",
        ],
    },
    {
        "slug": "pastoral-ministry",
        "name": "The Pastor's Role",
        "category": "Church Life",
        "hook": "Is the pastor primarily a preacher, a shepherd, a CEO — and how does the answer shape the health of a church?",
        "summary": "What the Bible teaches about pastoral ministry — shepherding, preaching, leadership, bivocational ministry, and the marks of a faithful pastor.",
        "keywords": [
            "pastor", "pastoral ministry", "shepherd", "bivocational",
            "pastor burnout", "pastoral leadership", "elder pastor",
            "what is a pastor", "senior pastor", "lead pastor",
            "clergy", "ordained ministry", "pastoral calling", "pastor role",
        ],
    },
    {
        "slug": "church-governance",
        "name": "Church Governance",
        "category": "Church Life",
        "hook": "Should churches be governed by elders, congregations, or bishops — and does polity really matter for church health?",
        "summary": "Evangelical debate over elder rule, congregationalism, and episcopal governance — and what the New Testament teaches about how churches should be structured and led.",
        "keywords": [
            "church governance", "church polity", "elder rule", "congregationalism",
            "episcopal", "elders", "deacons", "church structure", "plurality of elders",
            "church officers", "baptist polity", "presbyterian polity",
            "church constitution", "elder led church",
        ],
    },

    # Spiritual Formation
    {
        "slug": "singleness",
        "name": "Singleness",
        "category": "Spiritual Formation",
        "hook": "Is singleness a lesser life than marriage — or does the New Testament present it as an equally valid, even uniquely powerful, calling?",
        "summary": "Evangelical perspectives on singleness as a calling, celibacy as a gift, and how the church should honor and support single Christians.",
        "keywords": [
            "singleness", "single christian", "celibacy", "gift of singleness",
            "unmarried", "single in church", "sam allberry", "wesley hill",
            "barry danylak", "singleness and community", "christian single life",
            "loneliness and singleness", "single and satisfied",
        ],
    },
    {
        "slug": "biblical-literacy",
        "name": "Biblical Literacy",
        "category": "Spiritual Formation",
        "hook": "Why do so many Christians read the Bible so little — and what would change if the church actually knew Scripture?",
        "summary": "Evangelical concern about declining biblical knowledge, how Christians should read and engage Scripture, and what it looks like to recover genuine biblical literacy.",
        "keywords": [
            "biblical literacy", "bible reading", "scripture engagement", "read the bible",
            "bible knowledge", "old testament", "hermeneutics", "bible reading plan",
            "bible engagement", "word of god", "knowing scripture", "difficult passages",
            "biblical illiteracy", "whole bible",
        ],
    },
    {
        "slug": "pornography",
        "name": "Pornography & Sexual Purity",
        "category": "Spiritual Formation",
        "hook": "Is pornography primarily a spiritual problem, a neurological addiction, or both — and what does genuine freedom actually look like?",
        "summary": "Evangelical approaches to pornography addiction, purity culture critique, accountability, and the path to sexual wholeness for men and women.",
        "keywords": [
            "pornography", "porn addiction", "sexual purity", "purity culture",
            "lust", "sexual sin", "accountability software", "covenant eyes",
            "sexual wholeness", "porn and marriage", "purity movement",
            "sexual freedom", "masturbation", "sexual temptation",
        ],
    },
    {
        "slug": "death-and-dying",
        "name": "Death & Dying",
        "category": "Spiritual Formation",
        "hook": "How should Christians prepare for death — and does the church have anything distinctive to offer a culture that avoids it?",
        "summary": "Evangelical perspectives on dying well, end-of-life care, euthanasia, hospice, and how the hope of resurrection shapes the way Christians face death.",
        "keywords": [
            "death", "dying", "end of life", "dying well", "euthanasia",
            "assisted suicide", "hospice", "palliative care", "christian death",
            "resurrection hope", "mortality", "facing death", "good death",
            "death and resurrection", "christian funeral",
        ],
    },

    # Culture & Society
    {
        "slug": "christian-education",
        "name": "Christian Education",
        "category": "Culture & Society",
        "hook": "Should Christian parents put their children in public schools, Christian schools, or homeschool them — and is there a biblical answer?",
        "summary": "Evangelical debate over Christian schooling, classical education, homeschooling, and how families pass on faith through education.",
        "keywords": [
            "christian education", "homeschooling", "classical christian education",
            "christian school", "classical school", "faith and education",
            "charlotte mason", "classical conversations", "christian homeschool",
            "education worldview", "faith formation education", "christian curriculum",
            "school choice", "public school christian",
        ],
    },
    {
        "slug": "abortion",
        "name": "Abortion & the Pro-Life Movement",
        "category": "Culture & Society",
        "hook": "What does the pro-life movement owe to women after Roe — and is the church doing enough?",
        "summary": "Evangelical theology of life, the pro-life movement post-Dobbs, and what faithful Christian witness looks like on abortion in a post-Roe America.",
        "keywords": [
            "abortion", "pro-life", "roe v wade", "dobbs", "sanctity of life",
            "unborn", "personhood", "pregnancy center", "pro-life movement",
            "evangelical and abortion", "life begins at conception",
            "post-dobbs", "abortion ban", "pro-choice",
        ],
    },
    {
        "slug": "addiction-and-recovery",
        "name": "Addiction & Recovery",
        "category": "Culture & Society",
        "hook": "Is addiction a sin, a disease, or both — and what does the church offer that secular recovery programs cannot?",
        "summary": "How evangelical Christians understand addiction, the role of faith in recovery, and what the church can offer those struggling with substances and compulsive behaviors.",
        "keywords": [
            "addiction", "recovery", "celebrate recovery", "substance abuse",
            "alcoholism", "drug addiction", "faith and recovery", "christian recovery",
            "addiction and sin", "addiction and disease", "sobriety",
            "twelve steps", "freedom from addiction", "alcohol",
        ],
    },
    {
        "slug": "creation-care",
        "name": "Creation Care",
        "category": "Culture & Society",
        "hook": "Is caring for the environment a Christian responsibility — or a distraction from the gospel?",
        "summary": "Evangelical debate over environmental stewardship, climate change, and what it means to care for creation as image-bearers of God.",
        "keywords": [
            "creation care", "environment", "stewardship", "climate change",
            "evangelical environmentalism", "A Rocha", "care of creation",
            "environmental stewardship", "creation stewardship",
            "biblical ecology", "green christianity", "climate and faith",
        ],
    },
    {
        "slug": "christian-masculinity",
        "name": "Christian Masculinity",
        "category": "Culture & Society",
        "hook": "What does it actually mean to be a man in the church today — and is evangelical culture making men better or worse?",
        "summary": "Evangelical conversation about biblical manhood, the crisis of male disengagement from church, fatherhood, and what healthy Christian masculinity looks like.",
        "keywords": [
            "christian masculinity", "biblical manhood", "men in church",
            "male discipleship", "fatherhood", "men leaving church",
            "john eldredge", "wild at heart", "crisis of masculinity",
            "masculine christianity", "men and faith", "man up",
            "christian men", "gender and men",
        ],
    },

    {
        "slug": "stewardship-and-generosity",
        "name": "Stewardship & Generosity",
        "category": "Culture & Society",
        "hook": "Is tithing a law, a floor, or a ceiling — and what does radical gospel generosity actually demand of Christians?",
        "summary": "How Christians think about money, giving, and generosity — from tithing debates to radical generosity and the prosperity gospel critique.",
        "keywords": [
            "stewardship", "generosity", "tithing", "christian giving",
            "biblical stewardship", "randy alcorn", "treasure principle",
            "david platt radical", "tim keller generosity",
            "money and gospel", "tithing new testament",
            "christian finance", "giving church", "wealth and faith",
        ],
    },
]

# Index by slug for fast lookups
TOPICS_BY_SLUG = {t["slug"]: t for t in TOPICS}

# Group by category
CATEGORIES = ["Core Theology", "Church Life", "Spiritual Formation", "Culture & Society"]
TOPICS_BY_CATEGORY = {cat: [t for t in TOPICS if t["category"] == cat] for cat in CATEGORIES}
